OPENAI_API_KEY = "sua-chave-api-aqui"
ENVIRONMENT = "development"
STRIPE_SECRET_KEY = "sk_test_example"  # Chave temporária para testes
STRIPE_PRO_PRICE_ID = "price_test_pro"  # ID temporário para testes
STRIPE_UNLIMITED_PRICE_ID = "price_test_unlimited"  # ID temporário para testes
DOMAIN = "http://localhost:8501"  # Para desenvolvimento local
OPENAI_API_KEY = "sua_chave_openai_aqui"
